spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/bgw
    username: postgres
    password: Mpsedc@123
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
      database: posgresql
      database-platform: org.hibernate.dialect.PostgreSQLDialect
