spring:
  datasource:
    url: jdbc:postgresql://aws-0-ap-south-1.pooler.supabase.com:6543/postgres?user=postgres.fiityzwzpajxeypsiydw&password=7hhYc@6uzEd!X5@
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
      database: posgresql
      database-platform: org.hibernate.dialect.PostgreSQLDialect
