spring:
  datasource:
    url: jdbc:postgresql://roundhouse.proxy.rlwy.net:15745/railway
    username: postgres
    password: GabIFonxtsyuqLssfqeKDbkvzCjScoBs
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update  # Changed from create-drop to update for production use
    show-sql: true
    properties:
      hibernate:
        format_sql: true
      database: postgresql
      database-platform: org.hibernate.dialect.PostgreSQLDialect
